/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package florist.view;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class DashboardAdminView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonSignOut = new javax.swing.JButton();
        reportPanel1 = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ProductPanel1 = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        transactionPanel = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        buttonSignOut.setBackground(new java.awt.Color(255, 51, 51));
        buttonSignOut.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buttonSignOut.setText("Sign Out");
        buttonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignOutActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSignOut);
        buttonSignOut.setBounds(580, 500, 130, 30);

        reportPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportPanel1MouseClicked(evt);
            }
        });

        title3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        title3.setText("Report");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/florist/resource/chart-histogram (1).png"))); // NOI18N

        javax.swing.GroupLayout reportPanel1Layout = new javax.swing.GroupLayout(reportPanel1);
        reportPanel1.setLayout(reportPanel1Layout);
        reportPanel1Layout.setHorizontalGroup(
            reportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(35, 35, 35))
        );
        reportPanel1Layout.setVerticalGroup(
            reportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(title3)
                .addGap(28, 28, 28))
        );

        jPanel1.add(reportPanel1);
        reportPanel1.setBounds(780, 180, 200, 250);

        ProductPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductPanel1MouseClicked(evt);
            }
        });

        title2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        title2.setText("Product");
        title2.setInheritsPopupMenu(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/florist/resource/apps.png"))); // NOI18N

        javax.swing.GroupLayout ProductPanel1Layout = new javax.swing.GroupLayout(ProductPanel1);
        ProductPanel1.setLayout(ProductPanel1Layout);
        ProductPanel1Layout.setHorizontalGroup(
            ProductPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(35, 35, 35))
        );
        ProductPanel1Layout.setVerticalGroup(
            ProductPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(title2)
                .addGap(28, 28, 28))
        );

        jPanel1.add(ProductPanel1);
        ProductPanel1.setBounds(560, 180, 200, 250);

        transactionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionPanelMouseClicked(evt);
            }
        });

        title1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        title1.setText("Transaction");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/florist/resource/shopping-cart.png"))); // NOI18N

        javax.swing.GroupLayout transactionPanelLayout = new javax.swing.GroupLayout(transactionPanel);
        transactionPanel.setLayout(transactionPanelLayout);
        transactionPanelLayout.setHorizontalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(35, 35, 35))
        );
        transactionPanelLayout.setVerticalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(title1)
                .addGap(28, 28, 28))
        );

        jPanel1.add(transactionPanel);
        transactionPanel.setBounds(340, 180, 200, 250);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel5.setText("ADMIN DASHBOARD");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 80, 360, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/florist/resource/backgrounddashboard.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Rose Bouqet");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(330, 470, 202, 24);

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setText("Rp.99.999");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(330, 490, 140, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignOutActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure to sign out?", "Sign Out", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION){
            //Do nothing
        } else if (option == JOptionPane.YES_OPTION){
            SignInView loginView = new SignInView();
            loginView.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_buttonSignOutActionPerformed

    private void transactionPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionPanelMouseClicked
        ManajemenTransaksiView manajemenTransaksiView = new ManajemenTransaksiView();
        manajemenTransaksiView.setVisible(true);
    }//GEN-LAST:event_transactionPanelMouseClicked

    private void ProductPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductPanel1MouseClicked
        ManajemenProductView manajemenProductView = new ManajemenProductView();
        manajemenProductView.setVisible(true);
    }//GEN-LAST:event_ProductPanel1MouseClicked

    private void reportPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanel1MouseClicked
        ReportView reportView = new ReportView();
        reportView.setVisible(true);
    }//GEN-LAST:event_reportPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProductPanel1;
    private javax.swing.JButton buttonSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel reportPanel1;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JPanel transactionPanel;
    // End of variables declaration//GEN-END:variables
}
